import QtQml.Models 2.2

ListModel {
    ListElement{ firstName: "Adan"; lastName: "Gula"; favorite: true }
    ListElement{ firstName: "Alexandria"; lastName: "Armand"; favorite: false }
    ListElement{ firstName: "Alverta"; lastName: "Gorney"; favorite: false }
    ListElement{ firstName: "Annalisa"; lastName: "Dixion"; favorite: false }
    ListElement{ firstName: "Arlene"; lastName: "Drapeau"; favorite: false }
    ListElement{ firstName: "Ashely"; lastName: "Euler"; favorite: false }
    ListElement{ firstName: "Ashleigh"; lastName: "Terry"; favorite: false }
    ListElement{ firstName: "Audra"; lastName: "Vannorman"; favorite: false }
    ListElement{ firstName: "Bibi"; lastName: "Fraire"; favorite: false }
    ListElement{ firstName: "Branda"; lastName: "Melgoza"; favorite: false }
    ListElement{ firstName: "Breanna"; lastName: "Rotenberry"; favorite: false }
    ListElement{ firstName: "Brigette"; lastName: "Delk"; favorite: false }
    ListElement{ firstName: "Bruno"; lastName: "Raso"; favorite: false }
    ListElement{ firstName: "Calandra"; lastName: "Dudney"; favorite: true }
    ListElement{ firstName: "Carrol"; lastName: "Dedeaux"; favorite: false }
    ListElement{ firstName: "Celina"; lastName: "Bichrest"; favorite: false }
    ListElement{ firstName: "Celinda"; lastName: "Frutos"; favorite: false }
    ListElement{ firstName: "Celsa"; lastName: "Moen"; favorite: false }
    ListElement{ firstName: "Charise"; lastName: "Milan"; favorite: true }
    ListElement{ firstName: "Corazon"; lastName: "Burrus"; favorite: false }
    ListElement{ firstName: "Coreen"; lastName: "Dehner"; favorite: false }
    ListElement{ firstName: "Coretta"; lastName: "Stillwell"; favorite: false }
    ListElement{ firstName: "Cornell"; lastName: "Fierros"; favorite: false }
    ListElement{ firstName: "Deedee"; lastName: "Ruggerio"; favorite: false }
    ListElement{ firstName: "Demetrice"; lastName: "Mcclaren"; favorite: false }
    ListElement{ firstName: "Desiree"; lastName: "Marcano"; favorite: false }
    ListElement{ firstName: "Dimple"; lastName: "Harig"; favorite: false }
    ListElement{ firstName: "Divina"; lastName: "Fahie"; favorite: true }
    ListElement{ firstName: "Don"; lastName: "Thill"; favorite: false }
    ListElement{ firstName: "Ellena"; lastName: "Fredrick"; favorite: false }
    ListElement{ firstName: "Elmo"; lastName: "Routh"; favorite: false }
    ListElement{ firstName: "Elsie"; lastName: "Raulerson"; favorite: false }
    ListElement{ firstName: "Ervin"; lastName: "Bardsley"; favorite: false }
    ListElement{ firstName: "Estela"; lastName: "Alverson"; favorite: false }
    ListElement{ firstName: "Eufemia"; lastName: "Sheely"; favorite: true }
    ListElement{ firstName: "Fawn"; lastName: "Opie"; favorite: false }
    ListElement{ firstName: "Fred"; lastName: "Ralphs"; favorite: false }
    ListElement{ firstName: "Genevie"; lastName: "Spires"; favorite: false }
    ListElement{ firstName: "Genna"; lastName: "Quin"; favorite: false }
    ListElement{ firstName: "Gerri"; lastName: "Aden"; favorite: false }
    ListElement{ firstName: "Gianna"; lastName: "Shears"; favorite: false }
    ListElement{ firstName: "Gilda"; lastName: "Doyel"; favorite: false }
    ListElement{ firstName: "Glady"; lastName: "Peguero"; favorite: false }
    ListElement{ firstName: "Guy"; lastName: "Sondag"; favorite: false }
    ListElement{ firstName: "Herschel"; lastName: "Flowers"; favorite: false }
    ListElement{ firstName: "Hilda"; lastName: "Hamm"; favorite: false }
    ListElement{ firstName: "Hiroko"; lastName: "Mccarley"; favorite: false }
    ListElement{ firstName: "Jackeline"; lastName: "Millington"; favorite: false }
    ListElement{ firstName: "Jacqualine"; lastName: "Twiss"; favorite: false }
    ListElement{ firstName: "Jacquelyne"; lastName: "Worsley"; favorite: false }
    ListElement{ firstName: "Janelle"; lastName: "Broman"; favorite: false }
    ListElement{ firstName: "Jani"; lastName: "Reddish"; favorite: false }
    ListElement{ firstName: "Jasper"; lastName: "Krone"; favorite: false }
    ListElement{ firstName: "Jene"; lastName: "Gump"; favorite: false }
    ListElement{ firstName: "Jimmie"; lastName: "Cooley"; favorite: false }
    ListElement{ firstName: "Kellye"; lastName: "Wiest"; favorite: false }
    ListElement{ firstName: "Kristie"; lastName: "Jules"; favorite: false }
    ListElement{ firstName: "Kymberly"; lastName: "Moodie"; favorite: false }
    ListElement{ firstName: "Latesha"; lastName: "Netter"; favorite: false }
    ListElement{ firstName: "Lavelle"; lastName: "Lasala"; favorite: false }
    ListElement{ firstName: "Lesli"; lastName: "Czapla"; favorite: false }
    ListElement{ firstName: "Lorette"; lastName: "Prescott"; favorite: false }
    ListElement{ firstName: "Lorie"; lastName: "Hoeft"; favorite: false }
    ListElement{ firstName: "Lyndia"; lastName: "Schwalm"; favorite: false }
    ListElement{ firstName: "Mable"; lastName: "Marron"; favorite: false }
    ListElement{ firstName: "Marcelino"; lastName: "Spence"; favorite: false }
    ListElement{ firstName: "Marcie"; lastName: "Yopp"; favorite: false }
    ListElement{ firstName: "Margrett"; lastName: "Spagnuolo"; favorite: false }
    ListElement{ firstName: "Maris"; lastName: "Ruff"; favorite: false }
    ListElement{ firstName: "Marvella"; lastName: "Bowlby"; favorite: false }
    ListElement{ firstName: "Mauro"; lastName: "Winberg"; favorite: false }
    ListElement{ firstName: "Maybelle"; lastName: "Chute"; favorite: false }
    ListElement{ firstName: "Meghan"; lastName: "Burts"; favorite: false }
    ListElement{ firstName: "Micah"; lastName: "Hoggan"; favorite: false }
    ListElement{ firstName: "Mireille"; lastName: "Eastin"; favorite: false }
    ListElement{ firstName: "Mitsue"; lastName: "Ohler"; favorite: false }
    ListElement{ firstName: "Monica"; lastName: "Mccall"; favorite: false }
    ListElement{ firstName: "Morris"; lastName: "Cappel"; favorite: false }
    ListElement{ firstName: "Myong"; lastName: "Bale"; favorite: false }
    ListElement{ firstName: "Nannie"; lastName: "Poore"; favorite: false }
    ListElement{ firstName: "Noella"; lastName: "Gledhill"; favorite: false }
    ListElement{ firstName: "Ofelia"; lastName: "Bane"; favorite: true }
    ListElement{ firstName: "Phoebe"; lastName: "Bui"; favorite: false }
    ListElement{ firstName: "Quincy"; lastName: "Sweeting"; favorite: false }
    ListElement{ firstName: "Raguel"; lastName: "Ross"; favorite: false }
    ListElement{ firstName: "Raymundo"; lastName: "Headlee"; favorite: false }
    ListElement{ firstName: "Ressie"; lastName: "Helt"; favorite: false }
    ListElement{ firstName: "Rikki"; lastName: "Gilligan"; favorite: false }
    ListElement{ firstName: "Roselee"; lastName: "Swain"; favorite: false }
    ListElement{ firstName: "Shanda"; lastName: "Ballew"; favorite: false }
    ListElement{ firstName: "Stephine"; lastName: "Dimauro"; favorite: false }
    ListElement{ firstName: "Tamesha"; lastName: "Roop"; favorite: false }
    ListElement{ firstName: "Temple"; lastName: "Mcbain"; favorite: false }
    ListElement{ firstName: "Tiesha"; lastName: "Crumley"; favorite: false }
    ListElement{ firstName: "Tova"; lastName: "Kiel"; favorite: false }
    ListElement{ firstName: "Wade"; lastName: "Fossum"; favorite: false }
    ListElement{ firstName: "Willodean"; lastName: "Ferguson"; favorite: false }
    ListElement{ firstName: "Winfred"; lastName: "High"; favorite: false }
    ListElement{ firstName: "Winter"; lastName: "Furrow"; favorite: false }
    ListElement{ firstName: "Yvone"; lastName: "Edge"; favorite: true }
}
